### USERS
GET http://localhost:3100/api/users/6


###
POST http://localhost:3100/api/users
Content-Type: application/json

{
"first_name":"Test1",
"last_name":"Testons1",
"passport":"1234A",
"email":"test1@gmail.com",
"phone":"555444333",
"password":"1234",
"access_level":"user",
"membership":"wooden"
}

###
POST http://localhost:3100/api/users
Content-Type: application/json

{
"first_name":"Test2",
"last_name":"Testons2",
"passport":"1234B",
"email":"test2@gmail.com",
"phone":"555444333",
"password":"1234",
"access_level":"user",
"membership":"wooden"
}

###
POST http://localhost:3100/api/users
Content-Type: application/json

{
"first_name":"Test3",
"last_name":"Testons3",
"passport":"1234C",
"email":"test3@gmail.com",
"phone":"555444333",
"password":"1234",
"access_level":"user",
"membership":"wooden"
}



### Flights

### Get all
GET http://localhost:3100/api/flights

### Get by ID
GET http://localhost:3100/api/flights/2


### Full search / Works, but not through request.rest!
POST http://localhost:3100/api/flights/search

{
"origin_id": 1,
"destination_id": 3,
"departure": "2023-01-15"
}

###
POST http://localhost:3100/api/flights
Content-Type: application/json

{
"origin_id": 1,
"destination_id": 3,
"departure": "2023-12-15",
"arrival": "2023-12-15",
"duration": 2,
"price": 200,
"available_seats": 50,
"available_luggage": 300,
"terminal": 2,
"gate": 3,
"img": "https://cdn.insuremytrip.com/resources/29337/spain_travel_insurance_seville.jpg"
}

###
POST http://localhost:3100/api/flights
Content-Type: application/json

{
"origin_id": 3,
"destination_id": 2,
"departure": "2023-01-15",
"arrival": "2023-01-15",
"duration": 2,
"price": 500,
"available_seats": 50,
"available_luggage": 300,
"terminal": 1,
"gate": 7,
"img": "https://static.theceomagazine.net/wp-content/uploads/2023/06/26102050/48-hours-in-Bangkok1.jpg"
}

###
POST http://localhost:3100/api/flights
Content-Type: application/json

{
"origin_id": 3,
"destination_id": 1,
"departure": "2022-01-15",
"arrival": "2022-01-15",
"duration": 2,
"price": 500,
"available_seats": 50,
"available_luggage": 300,
"terminal": 1,
"gate": 7,
"img": "https://a.cdn-hotels.com/gdcs/production101/d154/ee893f00-c31d-11e8-9739-0242ac110006.jpg?impolicy=fcrop&w=800&h=533&q=medium"
}




### AIRPORTS

### Get all
GET http://localhost:3100/api/airports

### Get By ID
GET http://localhost:3100/api/airports/2


###
POST http://localhost:3100/api/airports
Content-Type: application/json

{
"name": "John F. Kennedy International Airport",
"name_acr": "JFK",
"city": "New York City",
"city_acr": "NYC",
"country": "United States",
"country_acr": "US",
"terminals": "6",
"gates": "128",
"img": "https://nyartlife.com/wp-content/uploads/2022/06/jfk-jpg.jpg"
}

###
POST http://localhost:3100/api/airports
Content-Type: application/json

  {
    "name": "Suvarnabhumi Airport",
    "name_acr": "BKK",
    "city": "Bangkok",
    "city_acr": "BKK",
    "country": "Thailand",
    "country_acr": "TH",
    "terminals": 2,
    "gates": 120,
    "img": "https://www.airport-technology.com/wp-content/uploads/sites/14/2002/09/Featured_Image_-_Suvarnabhumi_Airport_Thailand1.jpg"
  }


###
POST http://localhost:3100/api/airports
Content-Type: application/json

{
    "name": "León Airport",
    "name_acr": "LEN",
    "city": "León",
    "city_acr": "LEN",
    "country": "Spain",
    "country_acr": "ES",
    "terminals": 1,
    "gates": 5,
    "img": "https://www.airports-worldwide.com/img/spain/leon_spain_02.jpg"
}



















###
POST http://localhost:3100/api/airports
Content-Type: application/json

[
  {
    "name": "Suvarnabhumi Airport",
    "name_acr": "BKK",
    "city": "Bangkok",
    "city_acr": "BKK",
    "country": "Thailand",
    "country_acr": "TH",
    "terminals": 2,
    "gates": 120,
    "img": "https://example.com/suvarnabhumi_airport_image.jpg"
  },
  {
    "name": "Dubai International Airport",
    "name_acr": "DXB",
    "city": "Dubai",
    "city_acr": "DXB",
    "country": "United Arab Emirates",
    "country_acr": "AE",
    "terminals": 3,
    "gates": 200,
    "img": "https://example.com/dubai_airport_image.jpg"
  },
  {
    "name": "Los Angeles International Airport",
    "name_acr": "LAX",
    "city": "Los Angeles",
    "city_acr": "LAX",
    "country": "United States",
    "country_acr": "US",
    "terminals": 9,
    "gates": 130,
    "img": "https://example.com/lax_airport_image.jpg"
  },
  {
    "name": "Heathrow Airport",
    "name_acr": "LHR",
    "city": "London",
    "city_acr": "LON",
    "country": "United Kingdom",
    "country_acr": "UK",
    "terminals": 5,
    "gates": 120,
    "img": "https://example.com/heathrow_airport_image.jpg"
  },
  {
    "name": "Tokyo Haneda Airport",
    "name_acr": "HND",
    "city": "Tokyo",
    "city_acr": "TYO",
    "country": "Japan",
    "country_acr": "JP",
    "terminals": 4,
    "gates": 115,
    "img": "https://example.com/haneda_airport_image.jpg"
  }
]


